export const IGRPColors = {
  outline: {
    primary: {
      bg: 'bg-transparent',
      text: 'text-primary',
      textDark: 'dark:text-primary/40',
      border: 'border-primary',
      bgForeground: 'bg-primary',
      textBadge: 'text-primary',
      bgBadge: 'bg-transparent',
      borderBadge: 'border-primary',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary/10',
      borderCard: 'border-primary',
      alertText: 'text-primary',
      alertBg: 'bg-transparent',
      alertBorder: 'border-primary/50',
    },
    success: {
      bg: 'bg-transparent',
      text: 'text-emerald-700',
      textDark: 'dark:text-emerald-400',
      border: 'border-emerald-700',
      bgForeground: 'bg-emerald-600',
      textBadge: 'text-emerald-700',
      bgBadge: 'bg-transparent',
      borderBadge: 'border-emerald-700',
      textCard: 'text-emerald-500',
      bgCardIcon: 'bg-emerald-100',
      borderCard: 'border-emerald-500',
      alertText: 'text-emerald-600',
      alertBg: 'bg-transparent',
      alertBorder: 'border-emerald-500/50',
    },
    destructive: {
      bg: 'bg-transparent',
      text: 'text-red-600',
      textDark: 'dark:text-red-400',
      border: 'border-red-500',
      bgForeground: 'bg-red-500',
      textBadge: 'text-red-600',
      bgBadge: 'bg-transparent',
      borderBadge: 'border-red-600',
      textCard: 'text-red-500',
      bgCardIcon: 'bg-red-100',
      borderCard: 'border-red-500',
      alertText: 'text-red-600',
      alertBg: 'bg-transparent',
      alertBorder: 'border-red-500/50',
    },
    warning: {
      bg: 'bg-transparent',
      text: 'text-amber-600',
      textDark: 'dark:text-amber-400',
      border: 'border-amber-500',
      bgForeground: 'bg-amber-500',
      textBadge: 'text-amber-700',
      bgBadge: 'bg-transparent',
      borderBadge: 'border-amber-700',
      textCard: 'text-amber-500',
      bgCardIcon: 'bg-amber-100',
      borderCard: 'border-amber-500',
      alertText: 'text-amber-600',
      alertBg: 'bg-transparent',
      alertBorder: 'border-amber-500/50',
    },
    info: {
      bg: 'bg-transparent',
      text: 'text-blue-600',
      textDark: 'dark:text-blue-400',
      border: 'border-blue-500',
      bgForeground: 'bg-blue-500',
      textBadge: 'text-blue-700',
      bgBadge: 'bg-transparent',
      borderBadge: 'border-blue-700',
      textCard: 'text-blue-500',
      bgCardIcon: 'bg-blue-100',
      borderCard: 'border-blue-500',
      alertText: 'text-blue-600',
      alertBg: 'bg-transparent',
      alertBorder: 'border-blue-500/50',
    },
    secondary: {
      bg: 'bg-transparent',
      text: 'text-gray-700',
      textDark: 'dark:text-gray-300',
      border: 'border-black',
      bgForeground: 'bg-gray-500',
      textBadge: 'text-gray-700',
      bgBadge: 'bg-transparent',
      borderBadge: 'border-gray-700',
      textCard: 'text-gray-500',
      bgCardIcon: 'bg-gray-100',
      borderCard: 'border-gray-500',
      alertText: 'text-gray-600',
      alertBg: 'bg-transparent',
      alertBorder: 'border-gray-500/50',
    },
    indigo: {
      bg: 'bg-transparent',
      text: 'text-purple-600',
      textDark: 'dark:text-purple-400',
      border: 'border-purple-500',
      bgForeground: 'bg-purple-500',
      textBadge: 'text-purple-700',
      bgBadge: 'bg-transparent',
      borderBadge: 'border-purple-700',
      textCard: 'text-purple-500',
      bgCardIcon: 'bg-purple-100',
      borderCard: 'border-purple-500',
      alertText: 'text-purple-600',
      alertBg: 'bg-transparent',
      alertBorder: 'border-purple-500/50',
    },
  },
  solid: {
    primary: {
      bg: 'bg-primary',
      text: 'text-foreground',
      textDark: '',
      border: 'border-primary',
      bgForeground: 'bg-primary',
      textBadge: 'text-muted-foreground',
      bgBadge: 'bg-primary',
      borderBadge: 'border-primary',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-white',
      alertBg: 'bg-primary',
      alertBorder: 'border-primary/50',
    },
    success: {
      bg: 'bg-emerald-800',
      text: 'text-emerald-600 dark:text-emerald-400',
      textDark: 'dark:text-emerald-400',
      border: 'border-emerald-800',
      bgForeground: 'bg-emerald-800',
      textBadge: 'text-emerald-800',
      bgBadge: 'bg-emerald-100',
      borderBadge: 'border-emerald-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-white',
      alertBg: 'bg-emerald-600',
      alertBorder: 'border-emerald-600/50',
    },
    destructive: {
      bg: 'bg-red-500',
      text: 'text-red-600 dark:text-red-400',
      textDark: 'dark:text-red-400',
      border: 'border-red-500',
      bgForeground: 'bg-red-800',
      textBadge: 'text-red-800',
      bgBadge: 'bg-red-100',
      borderBadge: 'border-red-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-white',
      alertBg: 'bg-red-600',
      alertBorder: 'border-red-600/50',
    },
    warning: {
      bg: 'bg-amber-500',
      text: 'text-amber-600 dark:text-amber-400',
      textDark: 'dark:text-amber-400',
      border: 'border-amber-500',
      bgForeground: 'bg-amber-800',
      textBadge: 'text-amber-800',
      bgBadge: 'bg-amber-100',
      borderBadge: 'border-amber-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-white',
      alertBg: 'bg-amber-600',
      alertBorder: 'border-amber-600/50',
    },
    info: {
      bg: 'bg-blue-500',
      text: 'text-blue-600 dark:text-blue-400',
      textDark: 'dark:text-blue-400',
      border: 'border-blue-500',
      bgForeground: 'bg-blue-800',
      textBadge: 'text-blue-800',
      bgBadge: 'bg-blue-100',
      borderBadge: 'border-blue-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-white',
      alertBg: 'bg-blue-600',
      alertBorder: 'border-blue-600/50',
    },
    secondary: {
      bg: 'bg-gray-500',
      text: 'text-gray-700 dark:text-gray-300',
      textDark: 'dark:text-gray-300',
      border: 'border-gray-500',
      bgForeground: 'bg-gray-800',
      textBadge: 'text-gray-800',
      bgBadge: 'bg-gray-100',
      borderBadge: 'border-muted-foreground/10',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-white',
      alertBg: 'bg-gray-600',
      alertBorder: 'border-gray-600/50',
    },
    indigo: {
      bg: 'bg-purple-500',
      text: 'text-purple-600 dark:text-purple-400',
      textDark: 'dark:text-purple-400',
      border: 'border-purple-500',
      bgForeground: 'bg-purple-800',
      textBadge: 'text-purple-800',
      bgBadge: 'bg-purple-100',
      borderBadge: 'border-purple-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-white',
      alertBg: 'bg-purple-600',
      alertBorder: 'border-purple-600/50',
    },
  },
  soft: {
    primary: {
      bg: 'bg-primary/10',
      text: 'text-primary',
      textDark: 'dark:text-primary/40',
      border: 'border-transparent',
      bgForeground: 'bg-primary',
      textBadge: 'text-primary',
      bgBadge: 'bg-primary/10',
      borderBadge: 'border-primary/10',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-primary-600',
      alertBg: 'bg-primary-50',
      alertBorder: 'bg-primary-100',
    },
    success: {
      bg: 'bg-emerald-100',
      text: 'text-emerald-600',
      textDark: 'dark:text-emerald-400',
      border: 'border-transparent',
      bgForeground: 'bg-emerald-500',
      textBadge: 'text-emerald-500',
      bgBadge: 'bg-emerald-100',
      borderBadge: 'border-emerald-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-emerald-600',
      alertBg: 'bg-emerald-50',
      alertBorder: 'bg-emerald-100',
    },
    destructive: {
      bg: 'bg-red-100',
      text: 'text-red-600',
      textDark: 'dark:text-red-400',
      border: 'border-transparent',
      bgForeground: 'bg-red-500',
      textBadge: 'text-red-500',
      bgBadge: 'bg-red-100',
      borderBadge: 'border-red-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-red-600',
      alertBg: 'bg-red-50',
      alertBorder: 'bg-red-100',
    },
    warning: {
      bg: 'bg-amber-100',
      text: 'text-amber-600',
      textDark: 'dark:text-amber-400',
      border: 'border-transparent',
      bgForeground: 'bg-amber-500',
      textBadge: 'text-amber-500',
      bgBadge: 'bg-amber-100',
      borderBadge: 'border-amber-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-amber-600',
      alertBg: 'bg-amber-50',
      alertBorder: 'bg-amber-100',
    },
    info: {
      bg: 'bg-blue-100',
      text: 'text-blue-600',
      textDark: 'dark:text-blue-400',
      border: 'border-transparent',
      bgForeground: 'bg-blue-500',
      textBadge: 'text-blue-500',
      bgBadge: 'bg-blue-100',
      borderBadge: 'border-blue-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-blue-600',
      alertBg: 'bg-blue-50',
      alertBorder: 'bg-blue-100',
    },
    secondary: {
      bg: 'bg-gray-100',
      text: 'text-gray-600',
      textDark: 'dark:text-gray-300',
      border: 'border-transparent',
      bgForeground: 'bg-gray-500',
      textBadge: 'text-gray-500',
      bgBadge: 'bg-gray-100',
      borderBadge: 'bg-gray-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-gray-600',
      alertBg: 'bg-gray-50',
      alertBorder: 'bg-gray-100',
    },
    indigo: {
      bg: 'bg-purple-100',
      text: 'text-purple-600',
      textDark: 'dark:text-purple-400',
      border: 'border-transparent',
      bgForeground: 'bg-purple-500',
      textBadge: 'text-purple-500',
      bgBadge: 'bg-purple-100',
      borderBadge: 'border-purple-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alertText: 'text-purple-600',
      alertBg: 'bg-purple-50',
      alertBorder: 'bg-purple-100',
    },
  },
};

export type IGRPColorType = typeof IGRPColors;
// use appearance instead of role
export type IGRPColorRole = keyof IGRPColorType;
export type IGRPColorVariants = keyof IGRPColorType['solid'];
export const IGRPColorObjectVariants = Object.keys(IGRPColors.solid) as IGRPColorVariants[];
export const IGRPColorObjectRole = Object.keys(IGRPColors) as IGRPColorRole[];

export const igrpColorText = (value: IGRPColorVariants) => {
  return IGRPColors['solid'][value].text;
};
