// TODO: REVIEW THIS COLORS

/**
 * Tailwind class mappings for color variants (outline, solid, soft).
 * Used for badges, alerts, cards, etc.
 */
export const IGRPColors = {
  outline: {
    primary: {
      bg: 'bg-transparent',
      text: 'text-primary',
      border: 'border-primary',
      bgForeground: 'bg-primary',
      badge: 'text-primary dark:text-primary-foreground border-primary',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary/10',
      borderCard: 'border-primary',
      alert: 'text-primary bg-transparent border-primary/50',
    },
    success: {
      bg: 'bg-transparent',
      text: 'text-emerald-700 dark:text-emerald-400',
      border: 'border-emerald-700',
      bgForeground: 'bg-emerald-600',
      badge: 'text-emerald-700 bg-transparent border-emerald-700',
      textCard: 'text-emerald-500',
      bgCardIcon: 'bg-emerald-100',
      borderCard: 'border-emerald-500',
      alert: 'text-emerald-600 bg-transparent border-emerald-500/50',
    },
    destructive: {
      bg: 'bg-transparent',
      text: 'text-red-600 dark:text-red-400',
      border: 'border-red-500',
      bgForeground: 'bg-red-500',
      badge: 'text-red-600 bg-transparent border-red-600',
      textCard: 'text-red-500',
      bgCardIcon: 'bg-red-100',
      borderCard: 'border-red-500',
      alert: 'text-red-600 bg-transparent border-red-500/50',
    },
    warning: {
      bg: 'bg-transparent',
      text: 'text-amber-600 dark:text-amber-400',
      border: 'border-amber-500',
      bgForeground: 'bg-amber-500',
      badge: 'text-amber-700 bg-transparent border-amber-700',
      textCard: 'text-amber-500',
      bgCardIcon: 'bg-amber-100',
      borderCard: 'border-amber-500',
      alert: 'text-amber-600 bg-transparent border-amber-500/50',
    },
    info: {
      bg: 'bg-transparent',
      text: 'text-blue-600 dark:text-blue-400',
      border: 'border-blue-500',
      bgForeground: 'bg-blue-500',
      badge: 'text-blue-700 bg-transparent border-blue-700',
      textCard: 'text-blue-500',
      bgCardIcon: 'bg-blue-100',
      borderCard: 'border-blue-500',
      alert: 'text-blue-600 bg-transparent border-blue-500/50',
    },
    secondary: {
      bg: 'bg-transparent',
      text: 'text-gray-700 dark:text-gray-300',
      border: 'border-black',
      bgForeground: 'bg-gray-500',
      badge: 'text-gray-700 bg-transparent border-gray-700',
      textCard: 'text-gray-500',
      bgCardIcon: 'bg-gray-100',
      borderCard: 'border-gray-500',
      alert: 'text-gray-600 bg-transparent border-gray-500/50',
    },
    indigo: {
      bg: 'bg-transparent',
      text: 'text-purple-600 dark:text-purple-400',
      border: 'border-purple-500',
      bgForeground: 'bg-purple-500',
      badge: 'text-purple-700 bg-transparent border-purple-700',
      textCard: 'text-purple-500',
      bgCardIcon: 'bg-purple-100',
      borderCard: 'border-purple-500',
      alert: 'text-purple-600 bg-transparent border-purple-500/50',
    },
  },
  solid: {
    primary: {
      bg: 'bg-primary',
      text: 'text-foreground',
      border: 'border-primary',
      bgForeground: 'bg-primary',
      badge: 'text-primary-foreground bg-foreground border-primary-foreground',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-background bg-primary border-primary/50',
    },
    success: {
      bg: 'bg-emerald-800',
      text: 'text-emerald-600 dark:text-emerald-400',
      border: 'border-emerald-800',
      bgForeground: 'bg-emerald-800',
      badge: 'text-emerald-100 bg-emerald-800 border-emerald-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-background bg-emerald-600 border-emerald-600/50',
    },
    destructive: {
      bg: 'bg-red-500',
      text: 'text-red-600 dark:text-red-400',
      border: 'border-red-500',
      bgForeground: 'bg-red-800',
      badge: 'text-red-100 bg-red-800 border-red-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-background bg-red-600 border-red-600/50',
    },
    warning: {
      bg: 'bg-amber-500',
      text: 'text-amber-600 dark:text-amber-400',
      border: 'border-amber-500',
      bgForeground: 'bg-amber-800',
      badge: 'text-amber-100 bg-amber-600 border-amber-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-background bg-amber-600 border-amber-600/50',
    },
    info: {
      bg: 'bg-blue-500',
      text: 'text-blue-600 dark:text-blue-400',
      border: 'border-blue-500',
      bgForeground: 'bg-blue-800',
      badge: 'text-blue-100 bg-blue-800 border-blue-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-background bg-blue-600 border-blue-600/50',
    },
    secondary: {
      bg: 'bg-gray-500',
      text: 'text-gray-700 dark:text-gray-300',
      border: 'border-gray-500',
      bgForeground: 'bg-gray-800',
      badge: 'text-gray-100 bg-gray-800 border-gray-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-background bg-gray-600 border-gray-600/50',
    },
    indigo: {
      bg: 'bg-purple-500',
      text: 'text-purple-600 dark:text-purple-400',
      border: 'border-purple-500',
      bgForeground: 'bg-purple-800',
      badge: 'text-purple-100 bg-purple-800 border-purple-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-background bg-purple-600 border-purple-600/50',
    },
  },
  soft: {
    primary: {
      bg: 'bg-primary/10',
      text: 'text-primary',
      border: 'border-transparent',
      bgForeground: 'bg-primary',
      badge: 'text-primary bg-primary/10 border-primary/10',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-primary-600 bg-primary-50 bg-primary-100',
    },
    success: {
      bg: 'bg-emerald-100',
      text: 'text-emerald-600 dark:text-emerald-400',
      border: 'border-transparent',
      bgForeground: 'bg-emerald-500',
      badge: 'text-emerald-500 bg-esmerald-100 border-emerald-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-emerald-600 bg-emerald-50 bg-emerald-100',
    },
    destructive: {
      bg: 'bg-red-100',
      text: 'text-red-600 dark:text-red-400',
      border: 'border-transparent',
      bgForeground: 'bg-red-500',
      badge: 'text-red-500 bg-red-100 border-red-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-red-600 bg-red-50 bg-red-100',
    },
    warning: {
      bg: 'bg-amber-100',
      text: 'text-amber-600 dark:text-amber-400',
      border: 'border-transparent',
      bgForeground: 'bg-amber-500',
      badge: 'text-amber-500',
      bgBadge: 'bg-amber-100',
      borderBadge: 'border-amber-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-amber-600 bg-amber-50 bg-amber-100',
    },
    info: {
      bg: 'bg-blue-100',
      text: 'text-blue-600 dark:text-blue-400',
      border: 'border-transparent',
      bgForeground: 'bg-blue-500',
      badge: 'text-blue-500 bg-blue-100 border-blue-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-blue-600 bg-blue-50 bg-blue-100',
    },
    secondary: {
      bg: 'bg-gray-100',
      text: 'text-gray-600 dark:text-gray-300',
      border: 'border-transparent',
      bgForeground: 'bg-gray-500',
      badge: 'text-gray-500 bg-gray-100 border-gray-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-gray-600 bg-gray-50 bg-gray-100',
    },
    indigo: {
      bg: 'bg-purple-100',
      text: 'text-purple-600 dark:text-purple-400',
      border: 'border-transparent',
      bgForeground: 'bg-purple-500',
      badge: 'text-purple-500 bg-purple-100 border-purple-100',
      textCard: 'text-primary',
      bgCardIcon: 'bg-primary',
      borderCard: 'border-primary',
      alert: 'text-purple-600 bg-purple-50 bg-purple-100',
    },
  },
};

/** Type of IGRPColors object. */
export type IGRPColorType = typeof IGRPColors;
/** Color role (outline, solid, soft). */
export type IGRPColorRole = keyof IGRPColorType;
/** Color variant (primary, success, destructive, etc.). */
export type IGRPColorVariants = keyof IGRPColorType['solid'];
/** All color variant keys. */
export const IGRPColorObjectVariants = Object.keys(IGRPColors.solid) as IGRPColorVariants[];
/** All color role keys. */
export const IGRPColorObjectRole = Object.keys(IGRPColors) as IGRPColorRole[];

/**
 * Returns the text class for a color variant (solid style).
 */
export const igrpColorText = (value: IGRPColorVariants) => {
  return IGRPColors['solid'][value].text;
};
