import type { IGRPMenuItemArgs } from "@igrp/framework-next-types";

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 1,
    code: "APP_MNE_HOME",
    name: "Home",
    type: "MENU_PAGE",
    position: 0,
    icon: "House",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/",
    parentCode: null,
    applicationCode: "APP_MNE",
    roles: [],
  },
  {
    id: 2,
    code: "APP_MNE_PARAM",
    name: "Parametrizações",
    type: "FOLDER",
    position: 1,
    icon: "SlidersHorizontal",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: "APP_MNE_PARAM",
    applicationCode: "APP_MNE",
    roles: [],
  },
  {
    id: 3,
    code: "TEST_PAGINA_EXTERNA",
    name: "Gestão de Países",
    type: "MENU_PAGE",
    position: 0,
    icon: "SlidersHorizontal",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/gestao-paises",
    parentCode: "APP_MNE_PARAM",
    applicationCode: "APP_MNE",
    roles: [],
  },
  {
    id: 4,
    code: "TEST_MENU_EXTERNO",
    name: "Gestão de Organizações Internacionais",
    type: "MENU_PAGE",
    position: 1,
    icon: "SlidersHorizontal",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/gestao-organizacoes",
    parentCode: "APP_MNE_PARAM",
    applicationCode: "APP_MNE",
    roles: [],
  },
  {
    id: 5,
    code: "APP_MNE_ACORDOS",
    name: "Gestão de Acordos",
    type: "MENU_PAGE",
    position: 2,
    icon: "SlidersHorizontal",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/gestao-acordos",
    parentCode: "APP_MNE_PARAM",
    applicationCode: "APP_MNE",
    roles: [],
  },
];
