image: docker:29.1.2
services:
  - name: docker:29.1.2-dind
    command: ['--tls=false', '--mtu=1240']
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://docker:2375
  DOCKER_REGISTRY: registry.nosi.cv
  DOCKER_PROJECT: igrp
  IMAGE_NAME: igrp-storybook
stages:
  - build
  - deploy
build_storybook_image:
  stage: build
  rules:
    - changes:
        - packages/design-system-storybook/*
      when: always
  only:
    - main
  script:
    - docker login -u "$DOCKER_REGISTRY_USERNAME" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
    - docker build -t $DOCKER_REGISTRY/$DOCKER_PROJECT/$IMAGE_NAME -f packages/design-system-storybook/Dockerfile .
    - docker tag $DOCKER_REGISTRY/$DOCKER_PROJECT/$IMAGE_NAME $DOCKER_REGISTRY/$DOCKER_PROJECT/$IMAGE_NAME:$CI_PIPELINE_ID
    - docker push $DOCKER_REGISTRY/$DOCKER_PROJECT/$IMAGE_NAME
    - docker push $DOCKER_REGISTRY/$DOCKER_PROJECT/$IMAGE_NAME:$CI_PIPELINE_ID
deploy_storybook:
  image: gcc:latest
  stage: deploy
  only:
    - main
  script:
    - |
      curl -u "$DEPLOY_USER:$DEPLOY_PASSWORD" \
        -X POST \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        'https://manager.nosi.cv/v3/project/c-kthdc:p-tn7qs/workloads/deployment:integration-hub:$IMAGE_NAME?action=redeploy'

