packages:
  - packages/**
  - templates/**
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true
patchedDependencies:
  storybook@10.6.0: patches/storybook@10.6.0.patch
