import fs from "node:fs";
import path from "node:path";
import { unstable_cache } from "next/cache";

import { logger } from "@/lib/errors";

export type GetRoutesResult = {
  appRoutes: string[];
  paramMapBody: string;
};

const EMPTY_ROUTES: GetRoutesResult = { appRoutes: [], paramMapBody: "" };

/**
 * Parses Next.js generated routes from .next/types/routes.d.ts.
 *
 * ## File structure (generated by Next.js)
 * The file contains TypeScript declarations:
 * - `type AppRoutes = "/" | "/login" | "/dashboard" | ...` (union of route strings)
 * - `interface ParamMap { "/dashboard/[id]": { id: string }; ... }` (dynamic params)
 *
 * ## Parsing logic
 * 1. AppRoutes: Regex captures the union body; split by "|", trim quotes, filter empty
 * 2. ParamMap: Regex captures the interface body (between braces) for IGRP access checks
 *
 * ## When file is missing
 * Before first build, the file may not exist. Returns empty arrays; IGRP works with no routes.
 */
async function getRoutesUncached(): Promise<GetRoutesResult> {
  const file = path.join(process.cwd(), ".next/types/routes.d.ts");

  try {
    const content = await fs.promises.readFile(file, "utf8");

    // Match: type AppRoutes = "..." | "..." | ... (until next type/interface)
    const appRoutesMatch = content.match(
      /type AppRoutes\s*=\s*([\s\S]*?)\n(?=type|interface)/,
    );

    if (!appRoutesMatch) {
      logger.warn("Could not find AppRoutes in routes.d.ts", { file });
      return EMPTY_ROUTES;
    }

    // Parse union: split by |, remove quotes and whitespace, drop empty/type lines
    const appRoutes = appRoutesMatch[1]
      .split("|")
      .map((r) => r.trim().replace(/"/g, ""))
      .filter((r) => r.length > 0 && !r.startsWith("type"));

    // Match: interface ParamMap { ... } (multiline, ^} = end of block)
    const paramMapMatch = content.match(/interface ParamMap\s*{([\s\S]*?)^}/m);

    if (!paramMapMatch) {
      logger.warn("Could not find ParamMap in routes.d.ts", { file });
      return { appRoutes, paramMapBody: "" };
    }

    const paramMapBody = paramMapMatch[1];

    return { appRoutes, paramMapBody };
  } catch (error) {
    logger.warn("Could not read routes file", {
      error: error instanceof Error ? error.message : String(error),
      file: path.join(process.cwd(), ".next/types/routes.d.ts"),
    });

    return EMPTY_ROUTES;
  }
}

/**
 * Reads Next.js generated routes from .next/types/routes.d.ts.
 * Cached for 60s to reduce file system reads during layout renders.
 *
 * @returns Promise with appRoutes and paramMapBody
 */
export const getRoutes = unstable_cache(getRoutesUncached, ["app-routes"], {
  revalidate: 60,
});
