import type { IGRPMenuItemArgs } from "@igrp/framework-next-types";

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 29,
    code: "GST",
    name: "Gestão",
    type: "GROUP",
    position: 0,
    icon: "",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: "",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 30,
    code: "GST_PEDIDO",
    name: "Gestão de Pedidos",
    type: "MENU_PAGE",
    position: 0,
    icon: "ArrowLeftRight",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/gestao-pedidos",
    parentCode: "GST",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 31,
    code: "GST_PREDIO",
    name: "Gestão de Prédio",
    type: "MENU_PAGE",
    position: 0,
    icon: "Building",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/gestao-predio",
    parentCode: "GST",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },

  // {
  //   id: 32,
  //   code: "ESCRITURAS",
  //   name: "Escrituras",
  //   type: "MENU_PAGE",
  //   position: 0,
  //   icon: "File",
  //   status: "ACTIVE",
  //   target: "_self",
  //   url: null,
  //   pageSlug: "/alienacao/escrituras",
  //   parentCode: "",
  //   applicationCode: "APP_SIMPLE_LAND",
  //   roles: [],
  // },
  {
    id: 53,
    code: "PARAMETRIZACOES",
    name: "Parametrizações",
    type: "FOLDER",
    position: 1,
    icon: "List",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 54,
    code: "PARAM_GST_DOMINIOS",
    name: "Gestão de Domínios",
    type: "MENU_PAGE",
    position: 0,
    icon: "",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/parametrizacoes/gestao-dominio",
    parentCode: "PARAMETRIZACOES",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 55,
    code: "PARAM_GST_ATOS",
    name: "Gestão de Atos",
    type: "MENU_PAGE",
    position: 0,
    icon: "",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/parametrizacoes/gestao-atos",
    parentCode: "PARAMETRIZACOES",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 56,
    code: "PARAM_GST_RESPONSAVEIS",
    name: "Gestão de Responsáveis",
    type: "MENU_PAGE",
    position: 0,
    icon: "",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/parametrizacoes/gestao-responsaveis",
    parentCode: "PARAMETRIZACOES",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 57,
    code: "PARAM_AVALIACAO",
    name: "Avaliação",
    type: "MENU_PAGE",
    position: 0,
    icon: "",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/parametrizacoes/avaliacao",
    parentCode: "PARAMETRIZACOES",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 58,
    code: "PARAM_TIPOS_TRANSMISSAO",
    name: "Tipos de Transmissão",
    type: "MENU_PAGE",
    position: 0,
    icon: "",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/parametrizacoes/tipo-transmissao",
    parentCode: "PARAMETRIZACOES",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 59,
    code: "PARAM_CONFIGURACAO_TAXAS",
    name: "Configuração de Taxas",
    type: "MENU_PAGE",
    position: 0,
    icon: "",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/parametrizacoes/taxa-iti",
    parentCode: "PARAMETRIZACOES",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
  {
    id: 100,
    code: "DOCUMENTACAO",
    name: "Documentação",
    type: "MENU_PAGE",
    position: 100,
    icon: "BookOpen",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: "/documentacao",
    parentCode: "",
    applicationCode: "APP_SIMPLE_LAND",
    roles: [],
  },
];
