import { IGRPMockDataAsync } from '@igrp/framework-next';

export const igrpMockDataProvider: IGRPMockDataAsync = {
  getHeaderData: async () => ({
    user: {
      id: '1',
      name: 'Demo User',
      email: 'demo@igrp.com',
      image: '/api/placeholder/40/40',
      role: 'Administrator',
      permissions: ['read', 'write', 'admin'],
      fullname: 'Demo User',
      username: 'demo.user',
      igrpUsername: 'demo.user',
      status: 'ACTIVE',
    },
    notifications: [
      {
        id: '1',
        title: 'Detecção Concluída',
        message: 'A análise de páginas foi concluída com sucesso',
        type: 'success',
        timestamp: new Date(),
        isRead: false
      },
      {
        id: '2',
        title: 'Novo Relatório',
        message: 'Relatório de permissões está disponível',
        type: 'info',
        timestamp: new Date(Date.now() - 3600000),
        isRead: false
      },
      {
        id: '3',
        title: 'Sistema Atualizado',
        message: 'IGRP CLI Next foi atualizado para v3.0.0',
        type: 'success',
        timestamp: new Date(Date.now() - 7200000),
        isRead: true
      }
    ],
    quickActions: [
      {
        id: '1',
        title: 'Nova Detecção',
        icon: 'plus',
        href: '/detector'
      },
      {
        id: '2',
        title: 'Relatórios',
        icon: 'file-text',
        href: '/analytics'
      },
      {
        id: '3',
        title: 'Configurações',
        icon: 'settings',
        href: '/settings'
      }
    ]
  }),
  getSidebarData: async () => ({
    menuItems: [
      {
        id: 1,
        name: 'Test Dashboard',
        type: 'FOLDER',
        position: 1,
        icon: 'AppWindow',
        status: 'ACTIVE',
        target: 'INTERNAL',
        url: null,
        parentId: null,
        applicationId: 1,
        resourceId: null,
        createdBy: 'admin',
        createdDate: '2022-01-01T12:00:00.000Z',
        lastModifiedBy: 'admin',
        lastModifiedDate: '2022-01-01T12:00:00.000Z',
      },
      {
        id: 2,
        name: 'Test Settings',
        type: 'MENU_PAGE',
        position: 1,
        icon: 'Settings2',
        status: 'ACTIVE',
        target: 'INTERNAL',
        url: '/system-settings',
        parentId: 1,
        applicationId: 1,
        resourceId: null,
        createdBy: 'admin',
        createdDate: '2022-01-01T12:00:00.000Z',
        lastModifiedBy: 'admin',
        lastModifiedDate: '2022-01-01T12:00:00.000Z',
      },
      {
        id: 3,
        name: 'Test Users',
        type: 'MENU_PAGE',
        position: 2,
        icon: 'UserCog',
        status: 'ACTIVE',
        target: 'INTERNAL',
        url: '/users',
        parentId: 1,
        applicationId: 1,
        resourceId: null,
        createdBy: 'admin',
        createdDate: '2022-01-01T12:00:00.000Z',
        lastModifiedBy: 'admin',
        lastModifiedDate: '2022-01-01T12:00:00.000Z',
      },
      {
        id: 4,
        name: 'Test Roles',
        type: 'EXTERNAL_PAGE',
        position: 2,
        icon: 'Users',
        status: 'ACTIVE',
        target: 'INTERNAL',
        url: '/roles',
        parentId: null,
        applicationId: 1,
        resourceId: null,
        createdBy: 'admin',
        createdDate: '2022-01-01T12:00:00.000Z',
        lastModifiedBy: 'admin',
        lastModifiedDate: '2022-01-01T12:00:00.000Z',
      },
      {
        id: 9,
        name: 'NOSi',
        type: 'EXTERNAL_PAGE',
        position: 4,
        icon: 'Activity',
        status: 'ACTIVE',
        target: 'INTERNAL',
        url: 'https://nosi.cv',
        parentId: null,
        applicationId: 1,
        resourceId: null,
        createdBy: 'admin',
        createdDate: '2022-01-01T12:00:00.000Z',
        lastModifiedBy: 'admin',
        lastModifiedDate: '2022-01-01T12:00:00.000Z',
      },
      {
        id: 5,
        name: 'Home',
        type: 'FOLDER',
        position: 3,
        icon: 'AppWindow',
        status: 'ACTIVE',
        target: 'INTERNAL',
        url: null,
        parentId: null,
        applicationId: 1,
        resourceId: null,
        createdBy: 'admin',
        createdDate: '2022-01-01T12:00:00.000Z',
        lastModifiedBy: 'admin',
        lastModifiedDate: '2022-01-01T12:00:00.000Z',
      },
      {
        id: 6,
        name: 'Settings',
        type: 'MENU_PAGE',
        position: 1,
        icon: 'Settings2',
        status: 'ACTIVE',
        target: 'INTERNAL',
        url: '/settings',
        parentId: 5,
        applicationId: 1,
        resourceId: null,
        createdBy: 'admin',
        createdDate: '2022-01-01T12:00:00.000Z',
        lastModifiedBy: 'admin',
        lastModifiedDate: '2022-01-01T12:00:00.000Z',
      },
    ],
    collapsed: false,
    user: {
      id: '1',
      igrpUsername: 'igrp.user',
      username: 'igrp.user',
      fullname: 'IGRP USER',
      name: 'IGRP USER',
      email: 'igrp.user@nosi.cv',
      roles: [],
      departments: [],
      apps: ['igrp-demo', 'igrp-test'],
      status: 'ACTIVE',
      signature: null,
      image: null,
      picture: null,
    },
    footerItems: [
      {
        id: 152,
        name: 'Settings',
        type: 'MENU_PAGE',
        position: 1,
        icon: 'Settings2',
        status: 'ACTIVE',
        target: 'INTERNAL',
        url: '/system-settings',
        parentId: 5,
        applicationId: 1,
        resourceId: null,
        createdBy: 'admin',
        createdDate: '2022-01-01T12:00:00.000Z',
        lastModifiedBy: 'admin',
        lastModifiedDate: '2022-01-01T12:00:00.000Z',
      },
    ],
  })
}; 