/**
 * Re-exports of sidebar primitives for collapsible app navigation.
 * @module
 */
import {
  Sidebar as IGRPSidebar,
  SidebarContent as IGRPSidebarContent,
  SidebarFooter as IGRPSidebarFooter,
  SidebarGroup as IGRPSidebarGroup,
  SidebarGroupAction as IGRPSidebarGroupAction,
  SidebarGroupContent as IGRPSidebarGroupContent,
  SidebarGroupLabel as IGRPSidebarGroupLabel,
  SidebarHeader as IGRPSidebarHeader,
  SidebarInput as IGRPSidebarInput,
  SidebarInset as IGRPSidebarInset,
  SidebarMenu as IGRPSidebarMenu,
  SidebarMenuAction as IGRPSidebarMenuAction,
  SidebarMenuBadge as IGRPSidebarMenuBadge,
  SidebarMenuButton as IGRPSidebarMenuButton,
  SidebarMenuItem as IGRPSidebarMenuItem,
  SidebarMenuSkeleton as IGRPSidebarMenuSkeleton,
  SidebarMenuSub as IGRPSidebarMenuSub,
  SidebarMenuSubButton as IGRPSidebarMenuSubButton,
  SidebarMenuSubItem as IGRPSidebarMenuSubItem,
  SidebarProvider as IGRPSidebarProvider,
  SidebarRail as IGRPSidebarRail,
  SidebarSeparator as IGRPSidebarSeparator,
  SidebarTrigger as IGRPSidebarTrigger,
  useSidebar as useIGRPSidebar,
} from '../ui/sidebar';

export {
  IGRPSidebarProvider,
  IGRPSidebar,
  IGRPSidebarTrigger,
  IGRPSidebarRail,
  IGRPSidebarInset,
  IGRPSidebarInput,
  IGRPSidebarHeader,
  IGRPSidebarFooter,
  IGRPSidebarSeparator,
  IGRPSidebarContent,
  IGRPSidebarGroup,
  IGRPSidebarGroupLabel,
  IGRPSidebarGroupAction,
  IGRPSidebarGroupContent,
  IGRPSidebarMenu,
  IGRPSidebarMenuItem,
  IGRPSidebarMenuButton,
  IGRPSidebarMenuAction,
  IGRPSidebarMenuBadge,
  IGRPSidebarMenuSkeleton,
  IGRPSidebarMenuSub,
  IGRPSidebarMenuSubItem,
  IGRPSidebarMenuSubButton,
  // eslint-disable-next-line react-refresh/only-export-components
  useIGRPSidebar,
};
