import { IGRPMenuItemArgs } from '@igrp/framework-next-types';

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = 
// [
//   {
//     id: 34,
//     code: "MAIN",
//     name: "Main",
//     type: "GROUP",
//     position: 0,
//     icon: "fa-layer-group",
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: null,
//     parentCode: null,
//     applicationCode: "APP_IGRP",
//     permissions: []
//   },
//   {
//     id: 35,
//     code: "HOME_PAGE",
//     name: "Home Page",
//     type: "SYSTEM_PAGE",
//     position: 0,
//     icon: null,
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: "home",
//     parentCode: "MAIN",
//     applicationCode: "APP_IGRP",    
//     permissions: []
//   },
//   {
//     id: 36,
//     code: "LIBRARIES",
//     name: "Libraries",
//     type: "SYSTEM_PAGE",
//     position: 1,
//     icon: null,
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: "libraries",
//     parentCode: "MAIN",
//     applicationCode: "APP_IGRP",   
//     permissions: []
//   },
//   {
//     id: 37,
//     code: "ACCESS_MANAGEMENT_GROUP",
//     name: "Access Management",
//     type: "GROUP",
//     position: 1,
//     icon: "fa-lock",
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: null,
//     parentCode: null,
//     applicationCode: "APP_IGRP",   
//     permissions: []
//   },
//   {
//     id: 38,
//     code: "APPS_MANAGEMENT",
//     name: "Apps Management",
//     type: "SYSTEM_PAGE",
//     position: 0,
//     icon: null,
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: "apps",
//     parentCode: "ACCESS_MANAGEMENT_GROUP",
//     applicationCode: "APP_IGRP",   
//     permissions: []
//   },
//   {
//     id: 39,
//     code: "ACCESS_MANAGEMENT_FOLDER",
//     name: "Access Management",
//     type: "FOLDER",
//     position: 1,
//     icon: "fa-folder",
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: null,
//     parentCode: "ACCESS_MANAGEMENT_GROUP",
//     applicationCode: "APP_IGRP",    
//     permissions: []
//   },
//   {
//     id: 40,
//     code: "USER_MANAGEMENT",
//     name: "User Management",
//     type: "SYSTEM_PAGE",
//     position: 0,
//     icon: null,
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: "users",
//     parentCode: "ACCESS_MANAGEMENT_FOLDER",
//     applicationCode: "APP_IGRP",    
//     permissions: []
//   },
//   {
//     id: 41,
//     code: "DEPARTMENT_MANAGEMENT",
//     name: "Department Management",
//     type: "SYSTEM_PAGE",
//     position: 1,
//     icon: null,
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: "departments",
//     parentCode: "ACCESS_MANAGEMENT_FOLDER",
//     applicationCode: "APP_IGRP",    
//     permissions: []
//   },
//   {
//     id: 42,
//     code: "SETTINGS",
//     name: "Settings",
//     type: "SYSTEM_PAGE",
//     position: 2,
//     icon: null,
//     status: "ACTIVE",
//     target: "_self",
//     url: null,
//     pageSlug: "settings",
//     parentCode: null,
//     applicationCode: "APP_IGRP",    
//     permissions: []
//   }
// ]

[
  {
    id: 43,
    code: "MEU_MENU_TEST",
    name: "Meu Menu Test",
    type: "MENU_PAGE",
    position: 0,
    icon: "AppWindow",
    status: "ACTIVE",
    target: "_self",
    url: "meu-menu-test",
    pageSlug: "meu-menu-test",
    parentCode: null,
    applicationCode: "APP_TEST_1",    
    permissions: []
  },
  {
    id: 46,
    code: "TEST_MENU_GRUPO",
    name: "Test MEnu Grupo",
    type: "FOLDER",
    position: 4,
    icon: "WrapText",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",    
    permissions: []
  },
  {
    id: 47,
    code: "TEST_PAGINA_EXTERNA",
    name: "Test Pagina Externa",
    type: "FOLDER",
    position: 0,
    icon: "AlarmClock",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",    
    permissions: []
  },
  {
    id: 45,
    code: "TEST_MENU_EXTERNO",
    name: "Test Menu Externo",
    type: "MENU_PAGE",
    position: 3,
    icon: "ZoomIn",
    status: "ACTIVE",
    target: "_self",
    url: "test-menu-externo",
    pageSlug: "test-menu-externo",
    parentCode: "TEST_MENU_GRUPO",
    applicationCode: "APP_TEST_1",
    createdBy: "ea274d21-2386-470f-b597-9af8cbd56651",   
    permissions: []
  },
  {
    id: 49,
    code: "TEST_EXTERNAL_PAGE",
    name: "Test External Page",
    type: "EXTERNAL_PAGE",
    position: 0,
    icon: "MoveUpLeft",
    status: "ACTIVE",
    target: "_blank",
    url: "https://nosi.cv",
    pageSlug: "test-external-page",
    parentCode: "TEST_PAGINA_EXTERNA",
    applicationCode: "APP_TEST_1",    
    permissions: []
  }
]