import { IGRPMenuItemArgs } from '@igrp/framework-next-types';

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 43,
    code: 'MEU_MENU_TEST',
    name: 'Meu Menu Test',
    type: 'MENU_PAGE',
    position: 0,
    icon: 'AppWindow',
    status: 'ACTIVE',
    target: '_self',
    url: 'meu-menu-test',
    pageSlug: 'meu-menu-test',
    parentCode: null,
    applicationCode: 'APP_TEST_1',
    roles: [],
  },
  {
    id: 46,
    code: 'TEST_MENU_GRUPO',
    name: 'Test MEnu Grupo',
    type: 'FOLDER',
    position: 4,
    icon: 'WrapText',
    status: 'ACTIVE',
    target: '_self',
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: 'APP_TEST_1',
    roles: [],
  },
  {
    id: 47,
    code: 'TEST_PAGINA_EXTERNA',
    name: 'Test Pagina Externa',
    type: 'FOLDER',
    position: 0,
    icon: 'AlarmClock',
    status: 'ACTIVE',
    target: '_self',
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: 'APP_TEST_1',
    roles: [],
  },
  {
    id: 45,
    code: 'TEST_MENU_EXTERNO',
    name: 'Test Menu Externo',
    type: 'MENU_PAGE',
    position: 3,
    icon: 'ZoomIn',
    status: 'ACTIVE',
    target: '_self',
    url: 'test-menu-externo',
    pageSlug: 'test-menu-externo',
    parentCode: 'TEST_MENU_GRUPO',
    applicationCode: 'APP_TEST_1',
    createdBy: 'ea274d21-2386-470f-b597-9af8cbd56651',
    roles: [],
  },
  {
    id: 49,
    code: 'TEST_EXTERNAL_PAGE',
    name: 'Test External Page',
    type: 'EXTERNAL_PAGE',
    position: 0,
    icon: 'MoveUpLeft',
    status: 'ACTIVE',
    target: '_blank',
    url: 'https://nosi.cv',
    pageSlug: 'test-external-page',
    parentCode: 'TEST_PAGINA_EXTERNA',
    applicationCode: 'APP_TEST_1',
    roles: [],
  },
];
