import { IGRPMenuItemArgs } from '@igrp/framework-next-types';

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  {
    id: 1,
    name: 'Test Dashboard',
    type: 'FOLDER',
    position: 1,
    icon: 'AppWindow',
    status: 'ACTIVE',
    url: null,
    applicationCode: 'APPIGRPDEMO2',
    code: 'MENU_A',
    permissions: [],
  },
  {
    id: 2,
    name: 'Test Settings',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    url: '/system-settings',
    applicationCode: 'APPIGRPDEMO2',
    code: 'MENU_B',
    permissions: [],
  },
  {
    id: 3,
    name: 'Test Users',
    type: 'MENU_PAGE',
    position: 2,
    icon: 'UserCog',
    status: 'ACTIVE',
    url: '/users',
    applicationCode: 'APPIGRPDEMO2',
    code: 'MENU_C',
    permissions: [],
  },
  {
    id: 4,
    name: 'Test Roles',
    type: 'EXTERNAL_PAGE',
    position: 2,
    icon: 'Users',
    status: 'ACTIVE',
    url: '/roles',
    applicationCode: 'APPIGRPDEMO2',
    code: 'MENU_D',
    permissions: [],
  },
  {
    id: 5,
    name: 'Home',
    type: 'FOLDER',
    position: 3,
    icon: 'AppWindow',
    status: 'ACTIVE',
    url: null,
    applicationCode: 'APPIGRPDEMO2',
    code: 'MENU_E',
    permissions: [],
  },
  {
    id: 6,
    name: 'Settings',
    type: 'MENU_PAGE',
    position: 1,
    icon: 'Settings2',
    status: 'ACTIVE',
    url: '/system-settings',
    applicationCode: 'APPIGRPDEMO2',
    code: 'MENU_F',
    permissions: [],
  },
];
